ans-group/sdk-php

src/Client.php
tests/ClientTest.php

See #4 
* Added get/post/put/patch/delete methods
* Changed request method to remove body if `POST`, `PATCH` or `DELETE`. Stops guzzle warning

Added methods to client class for each supported HTTP method type

---

src/Page.php
tests/PageTest.php

See #10 
* `getNextPage` and `getLastPage` methods now return false early if there is no next/previous page link

Added early return for page traversal methods

---

src/Client.php
tests/ClientTest.php

* Changed header logic to use guzzle config. This should allow users to pass a custom guzzle client in, and it will use the custom headers instead of overwriting them

Changed header logic to use guzzle config

---

src/Pss/Client.php
src/Pss/Request.php
tests/PssClientTest.php

* Adds customerReference attribute to the PSS Request object which is based on `customer_reference` on API responses
* Added Docblocks to Request class to be consistent with other classes
Resolves #30

Added customerReference attribute to PSS Request object

---

src/PSS/RequestClient.php
tests/PssClientTest.php

I have changed createdAt on the Request class to be a DateTime rather than the string it was before, I have then added tests to cover this change.
closes #45

Ensure createdAt is always a DateTime

---

README.md

as we prepare to tag version one, lets remove the beta notice to let users know no significant changes will occur after this point

remove BETA notice

---

src/PSS/Client.php
src/PSS/ReplyClient.php
tests/PssClientTest.php

The conversation endpoint was changed to replies (though conversation does still work). To be consistent with the documentation I have changed the SDK to use the newer replies endpoint
Closes #66

Change conversation to replies

---

src/PSS/Entities/Author.php
src/PSS/Entities/Reply.php
src/PSS/ReplyClient.php
src/SelfResponse.php
tests/SelfResponseTest.php

Resolves #68 
Example Usage:
```php
<?php
require_once "./vendor/autoload.php";
$author = new \UKFast\SDK\PSS\Entities\Author;
$author->id = 1;
$reply = new \UKFast\SDK\PSS\Entities\Reply;
$reply->author = $author;
$reply->description = "test description goes here\nwith a new line";
$pss = (new \UKFast\SDK\PSS\Client)->auth('REDACTED');
try {
$response = $pss->replies()->create(1, $reply);
} catch (\UKFast\SDK\Exception\ApiException $e) {
var_dump($e->getErrors());
} catch (\Exception $e) {
var_dump($e->getMessage());
}
```

Added SelfResponse page type, added ability to reply to a PSS request

---

src/PSS/Entities/Product.php
src/PSS/Entities/Request.php
src/PSS/RequestClient.php

Example usage:
```php
<?php
require_once "./vendor/autoload.php";
$author = new \UKFast\SDK\PSS\Entities\Author;
$author->id = 1;
$product = new \UKFast\SDK\PSS\Entities\Product;
$product->type = 'Domains';
$product->id = 100;
$request = new \UKFast\SDK\PSS\Entities\Request();
$request->author = $author;
$request->product = $product;
$request->subject = 'test sdk subject';
$request->details = "Test\nTest";
$request->priority = "High";
$pss = (new \UKFast\SDK\PSS\Client)->auth(***');
try {
$response = $pss->requests()->create($request);
var_dump($response->get());
} catch (\UKFast\SDK\Exception\ApiException $e) {
var_dump($e->getErrors());
} catch (\Exception $e) {
var_dump($e->getMessage());
}
```

Added ability to create a support request

---

src/Account/Client.php
src/Account/Entities/Invoice.php
src/Account/Entities/InvoiceQuery.php
src/Account/InvoiceClient.php
src/Account/InvoiceQueryClient.php
tests/Account/InvoiceQueryTest.php
tests/Account/InvoiceTest.php

- Added `Invoice` and `InvoiceQuery` clients and entities.
- Added tests for `get` and `getById` requests and for the `SelfResponse` function on InvoiceQuery responses.

Add Invoice and InvoiceQuery to the SDK

---

src/LTaaS/AgreementClient.php
src/LTaaS/Client.php
src/LTaaS/DomainClient.php
src/LTaaS/Entities/Agreement.php
src/LTaaS/Entities/Domain.php
src/LTaaS/Entities/Job.php
src/LTaaS/Entities/Test.php
src/LTaaS/Entities/TestAuthorisation.php
src/LTaaS/JobClient.php
src/LTaaS/TestClient.php

Create the Entites that are required for a test to be authorised on creation. Also alter the returned data for the create methods on a test and job to use SelfResponse.

Create entities and methods for authorisation agreements

---

src/PaginationUrl.php
tests/PaginationUrlTest.php

Previously, if you passed a url that already had a query parameter in it, it would incorrectly mangle the page query params onto it, e.g.
`my-enpdoint?param=here` would output `my-enpdoint?param=herepage=1&per_page=10`
This change checks if there is a query param present already and handles it appropriately

Can now pass urls with query strings to PaginationUrl

---

src/Client.php
src/Exception/ApiException.php
src/Page.php

I've updated the InvalidJsonExceptions to accept the invalid json body as the message. This'll give more helpful error messages than '4'

Now sets the invalid json string as the invalid json exception message

---

src/Account/InvoiceQueryClient.php

We changed the endpoint from `/invoices/query/{id}` to `/invoice-queries/{id}`.
This PR reflects this in our SDK.

Update InvoiceQuery endpoint

---

src/SSL/Entities/Report.php
src/SSL/Entities/ReportCertificate.php
src/SafeDNS/Entities/Note.php
src/SafeDNS/Entities/Record.php
src/SafeDNS/Entities/Zone.php

We remove the properties themselves very quickly for a bug fix, so this
adds IDE typehinting back in

Add Docblocks Back to Entities Extending The Base

---

src/SSL/Client.php

This now matches the rest of the clients, looks like it was missed when this functionality was added

Add SSl Report Shortcut

---

src/Account/Entities/InvoiceQuery.php
src/Account/InvoiceQueryClient.php
tests/Account/InvoiceQueryTest.php

This MR adds the `getPage` method to the `InvoiceQueryClient`.
It also adds extra properties for Invoice Queries - namely the resolution information, the resolution date, and the status of the query.

Add getPage method and resolution properties for Invoice Queries

---

.travis.yml

We need to add PHP 7.3 to the TravisCI config so our PRs are tested against all the version they are likely to be used with.

Add php73 to TravisCI config

---

composer.json
src/DDoSX/Client.php
src/DDoSX/DomainVerificationClient.php
src/DDoSX/Entities/VerificationFile.php
tests/DDoSX/DomainVerificationTest.php

I would like to verify domains via the SDK, these are the methods which I'll need to do that with.
Testing instructions:

Add DDoSX Verification Methods

---

src/Billing/Entities/RecurringCost.php

We currently use the PSS Product entity in Billing but we should use the Billing Product entity to allow us to diverge implementations in the future.

Use Billing Product entity instead of PSS Product entity

---

src/Entity.php

We would be able to perform an null check on the value, rather that it erroring or returning `false`, which is less useful.

Add handler for unsupported date format

---

src/Billing/CloudCostClient.php

This fixes the following error:
```
Cannot use UKFast\SDK\Client as Client because the name is already in use
--
in CloudCostClient.php line 7
```

Add BaseClient alias to CloudCostClient extension

---

src/eCloud/Entities/Pod.php
src/eCloud/PodClient.php
tests/eCloud/PodTest.php

- Updates the PodClient to load the Pod using the base Entity
- Updates PodClient to implement ClientEntityInterface so that we can return the admin version of the pod entity in the admin client.

Update PodClient to load Pod using base Entity

---

src/Billing/Entities/PaymentCard.php
tests/Billing/PaymentCardClientTest.php
tests/Billing/PaymentCardTest.php

Remove the automatic date formatting from the validFrom and expiry m/y fields.

Remove date formatting from validFrom/expiry

---

src/Billing/Client.php
src/Billing/Entities/InvoiceQuery.php
src/Billing/InvoiceQueryClient.php
tests/Billing/InvoiceQueryClientTest.php

This PR adds:
- `getPage()`
- `getById()`
- `create()`

Add InvoiceQuery endpoints to Billing SDK

---

src/DDoSX/SslClient.php

Here we should use a inheritable and overridable method for serializing into a Ssl or AdminSsl entity depending on whether the client is accessed through the Admin SDK

Allow for DDoSX SSL entity serialisation based on admin access

---

src/DDoSX/SslClient.php
tests/DDoSX/SslClientTest.php

The getById method has not yet been added to the public client class. Adding it makes the SSL client methods consistent with those available in the other client classes

Add getById method to the DDoSX SSL client class

---

src/DDoSX/RecordClient.php

For https://gitlab.devops.ukfast.co.uk/ukfast/myukfast/myukfast/issues/2644
This merge request adds the `destroy` method for a DDoSX Record. It will be used to allow the user to delete a record using the MyUKFast pages implemented in the issue linked above

Add missing record destroy method

---

src/Entity.php

This PR adds the `DateTime::ATOM` format into the Entity set method. With a fallback to the current `DateTime::ISO8601` default.

Add DateTime::ATOM format into Entity::set()

---

src/DRaaS/Entities/Replica.php

Following minor spec change the hdd attribute has been renamed to disk to prevent client confusion.
DRAAS#83

hdd attribute renamed to disk

---

src/Client.php

At the moment we don't support passing `$body` or `$headers` to the paginatedRequest method even though it's supported properly by the underlying request method.
This PR introduces this functionality with sensible defaults of `null` and `[]` respectively.

Support body and headers on paginatedRequest

---

src/ThreatMonitoring/Client.php
src/ThreatMonitoring/Entities/ActiveResponseBlockedAttacks.php
src/ThreatMonitoring/Entities/AttackingCountriesList.php
src/ThreatMonitoring/Entities/ScaScoreAverage.php
src/ThreatMonitoring/Entities/TopBruteForceUsernamesList.php
src/ThreatMonitoring/Reporting/ActiveResponseClient.php
src/ThreatMonitoring/Reporting/AttackingCountriesClient.php
src/ThreatMonitoring/Reporting/AttackingIpsClient.php
src/ThreatMonitoring/Reporting/ScaClient.php
src/ThreatMonitoring/Reporting/TopBruteForceUsernamesClient.php
src/eCloud/Entities/Volume.php
src/eCloud/VolumeClient.php

This adds the reporting endpoints for the new Attacks dashboard for Threat Vision,
The new metrics are:
- total blocked attacks,
- list of top attacking countries,
- list of top brute force usernames,
- average SCA score,
- active response blocked attacks list,
- total blocked IPs,
- list of blocked IPs

Threatmon feature request 8 active response blocked dashboards

---

src/Loadbalancers/ListenerClient.php

I've tested this by editing the file in my vendor folder and creating, and updating listeners and also editing GeoIP settings. I don't think this change was actually needed in the final implementation of GeoIP and it's causing validation to fail as `cluster_id` is sent as `clusterId` without the map

Add map back to listener client

---

src/SafeDNS/RecordClient.php

This will now map in the priority. It should be updated to use the new mapping method in the future to avoid this

Fix Record Client Entity Hydration

---

src/eCloud/Entities/Instance.php
src/eCloud/InstanceClient.php

This MR adds support for backup_vm_enabled and backup_agent_enabled properties on instances. This MR also moves the Instance entity map to the entity class.

support for new eCloud Instance backup properties
