ans-group/sdk-php

src/Client.php
tests/ClientTest.php

See #2 
* Added default headers to default guzzle client
* Added logic to put user agent into headers when sending request

Changed default user-agent to UKFast/1.0

---

src/Client.php
tests/ClientTest.php

See #8 
* Only removes POST body if it's empty

Only removes POST body when empty

---

src/Domains/Client.php

Added domain whois raw method to domain client

---

src/Account/Client.php
src/Domains/Client.php
src/Pss/Client.php
src/SSL/Client.php

* Went through and made everything consistent with what eCloud clients were doing
Resolves #20

Made requests use guzzle base path

---

src/Client.php

closes https://github.com/ukfast/sdk-php/issues/15

set default content type to application/json for post/put/patch requests

---

src/PaginationUrl.php
tests/PaginationUrlTest.php

Resolves #32
Not sure if there's a better alternative to var_export? Happy to change if anyone has any better ideas :)

var_export boolean filters to stop them being converted to 1 & 0

---

src/Client.php
src/PSS/Client.php

Set PSS to auth when clients are created

---

src/Exception/ApiException.php
src/PHaaS/CampaignClient.php
src/PHaaS/Entities/Template.php

Fixes an issue with the ApiException and details
Adds properties Templates
Updates the Url for campaign details and reporting

fixes issue with ApiException and updates PHaaS urls

---

src/PSS/ConversationClient.php
src/PSS/Entities/Attachment.php
src/PSS/Entities/Reply.php
tests/Pss/AttachmentTest.php
tests/PssClientTest.php

Added attachments list to conversation endpoint

---

src/PHaaS/DomainClient.php

Switched the verify domain endpoint from a get request to a post request

Switched the verify domain hash endpoint verb

---

examples/safedns/zoneDetail.php
examples/safedns/zoneList.php
examples/safedns/zoneRecords.php
src/SafeDNS/Client.php
src/SafeDNS/Entities/Record.php
src/SafeDNS/Entities/Zone.php
src/SafeDNS/RecordClient.php
src/SafeDNS/ZoneClient.php

initial support for listing zones and records

Initial safedns support

---

src/LTaaS/Client.php
src/LTaaS/DomainClient.php
src/LTaaS/Entities/Job.php
src/LTaaS/Entities/Scenario.php
src/LTaaS/Entities/Test.php
src/LTaaS/Entities/Threshold.php
src/LTaaS/JobClient.php
src/LTaaS/ScenarioClient.php
src/LTaaS/TestClient.php
src/LTaaS/ThresholdClient.php

Add all the required clients and entities to create a Load Testing Test via the APIO

Create a new test endpoint

---

src/LTaaS/Entities/Domain.php
src/LTaaS/Entities/Test.php

Add verification method field to the Domain entity and protocol field to the Test entity

Add fields to domain entity

---

src/Client.php
src/LTaaS/Entities/JobResults.php
src/LTaaS/Entities/JobSettings.php
src/LTaaS/Entities/Scenario.php
src/LTaaS/JobClient.php

Create the methods required to get the settings and the results for a test.

Return test results from the api

---

src/LTaaS/Entities/Domain.php
src/LTaaS/Entities/Job.php
src/LTaaS/Entities/Test.php
src/LTaaS/JobClient.php
src/LTaaS/TestClient.php

The response data has changed so the SDK required some changes to get it up to date with the current API version.

Fix inconsistencies between the sdk and api responses

---

src/Client.php

Fixes error in conditional in client request for request body

Fixes error in conditional in client request for request body

---

src/eCloud/DatastoreClient.php

Fixes wrongly assigned property on datastore entity

Fixes wrongly assigned property on Datastore entity

---

src/Account/Entities/Invoice.php
src/Account/Entities/InvoiceQuery.php
src/Account/InvoiceQueryClient.php
tests/Account/InvoiceQueryTest.php
tests/Account/InvoiceTest.php

- Updated `Invoice` entity to use new properties.
- Updated tests.

Update Invoice Client to use new API response

---

src/SSL/ReportClient.php

Updated the filed from the api to match the current live response

updated covers_domain field

---

src/SSL/ReportClient.php

Needed to make a field match the live api repsonse

updated chain_passed to chain_intact to match new response

---

src/eCloud/SolutionClient.php
tests/eCloud/SolutionTest.php

Get all solutions

---

src/Client.php
src/Entities/Entity.php
src/Entity.php
src/PSS/Entities/Attachment.php
src/PSS/Entities/Author.php
src/PSS/Entities/Download.php
src/PSS/Entities/Feedback.php
src/PSS/Entities/Product.php
src/PSS/Entities/Reply.php
src/PSS/Entities/Request.php
src/PSS/RequestClient.php
src/eCloud/Entities/Datastore.php
tests/EntityTest.php

Moves PSS over to the new entity class

PSS entity changes

---

src/DDoSX/Client.php
src/DDoSX/DomainClient.php
src/DDoSX/Entities/Domain.php
src/DDoSX/Entities/ExternalDns.php

This is the first step to implementing the rest of the DDoSX endpoints

Add Getting Of DDoSX Domains

---

src/Client.php
src/Page.php

Fix docblock exceptions

---

src/eCloud/Client.php
src/eCloud/DatastoreClient.php
src/eCloud/Entities/Iops.php
src/eCloud/IopsClient.php
tests/eCloud/IopsTest.php

Adds basic IOPS tiers client and get endpoints

Iops client

---

src/eCloud/Entities/Iops.php

update iops entity to new entity format

Iops client entity update

---

src/PSS/Entities/Reply.php
src/PSS/ReplyClient.php
tests/PssClientTest.php

* Added request_id to Reply entity
* Added ability to hit `GET v1/replies` endpoint
Diff size should go down once https://github.com/ukfast/sdk-php/pull/141 has been merged

Reply Client updates

---

src/Client.php
src/Entity.php
src/PSS/Entities/Author.php
src/PSS/Entities/Request.php
src/PSS/RequestClient.php
src/eCloud/Entities/Iops.php
tests/ClientTest.php

Proposed changes for having friendly filter names
~~Not ready to merge yet, as I haven't had a chance to test it with existing systems~~

Friendly-name filter properties

---

src/Client.php
tests/ClientTest.php

- Support for API friendly names with filters and tests for them
- Tests for API friendly names not defined in the map

support for API friendly names with filters and tests for them

---

src/DDoSX/DomainClient.php

This was causing a namespace collision when I try to extend it

Alias DDoSX Client

---

src/eCloud/Client.php
tests/eCloud/ApplianceTest.php

refactors appliance to appliances

removes non-public appliance version

---

src/LTaaS/AccountClient.php
src/LTaaS/Client.php
src/LTaaS/Entities/Account.php
tests/Ltaas/AccountTest.php

- add the account entity
- add the account client 
- add the account create method

Add the create an account endpoint

---

src/Account/Entities/Credit.php

This is the expected new format which gives more functionality

Update Credit Entity

---

src/Account/CreditClient.php
tests/Account/CreditTest.php

First step in removing the legacy "getAll"

Add Paginated Response For Account Credits

---

.travis.yml

Support the latest PHP version

Make Travis Build Against PHP 7.4

---

src/Account/Entities/Company.php

We've surfaced a company's country in the API response, we should raise this in the SDK.

Surface country in Company entity

---

src/Entity.php
tests/EntityTest.php

This now plays much nicer with Laravel resource serialization

Make Entities Implement Core ArrayAccess Interface

---

src/DDoSX/CdnClient.php
src/DDoSX/DomainClient.php
src/DDoSX/WafClient.php

The API response is not inside an array, just the data response

Fix DDoSX Serialization Issue

---

src/Account/Client.php
src/Account/Entities/History.php
src/Account/HistoryClient.php

This adds support for the new history resource on the Accounts API.

Add support for history resource

---

src/SSL/CertificateClient.php
src/SSL/Entities/Certificate.php
tests/Ssl/SslCertificateTest.php

Bring SSL certificates up to the new format

Ssl Certificate Standardization

---

src/DDoSX/Client.php
src/DDoSX/Entities/Ssl.php
src/DDoSX/SslClient.php
tests/DDoSX/SslClientTest.php

I would like to list SSL certificates

Adds A DDoSX SSL Client

---

src/DDoSX/SslClient.php
tests/DDoSX/SslClientTest.php

This should nicely match the rest of the SDK's creation methods

Add DDoSX SSL Creation

---

src/Account/CreditClient.php

Added a function to get the credits for a service by the name

Add get credit by type

---

src/SafeDNS/Entities/Record.php
src/SafeDNS/RecordClient.php
tests/SafeDns/RecordClientTest.php

Bring this up to the current expected format of SDK creation methods

Update safedns record create

---

src/DRaaS/Client.php
src/DRaaS/Entities/Solution.php
src/DRaaS/SolutionClient.php
tests/DRaaS/SolutionTest.php

- Creates DRaaS Client
- Creates DRaaS solutions client
- GET Solutions, solutions/{id} endpoints

Draas get solutions

---

src/DRaaS/SolutionClient.php
tests/DRaaS/SolutionTest.php

- Adds iops_tier to entity on get solution/solutions endpoints, removes tenent_uid as it's admin only
- Adds solution update method

Solution iops tier

---

src/Billing/CloudCostClient.php
src/Billing/Entities/CloudCost.php
src/Billing/Entities/Resource.php
tests/Billing/CloudCostClientTest.php

Changes to SDK regarding cloud costs + tests added.

Cloud cost changes + tests

---

src/Entity.php
tests/EntityTest.php

This method clones an entity, and all the entities it holds.
This is really useful if you need a copy of the entity you can safely mutate without affecting the original

Added fresh method to entity class

---

examples/ecloud/podApplianceList.php
examples/ecloud/vmCreateAppliance.php
src/eCloud/Entities/VirtualMachine.php
src/eCloud/VirtualMachineClient.php

- added Appliance examples
- added some missing vm deploy properties

support deploying virtual machines from the eCloud Marketplace

---

src/Account/ClientClient.php

Added client delete method to the client sdk

Added client delete method

---

src/DRaaS/Entities/BackupService.php
src/DRaaS/SolutionClient.php

Adds getBackupService() method to SolutionClient

Draas backup service info

---

src/DRaaS/Client.php
src/DRaaS/Entities/IopsTier.php
src/DRaaS/IopsTiersClient.php

Functionality for get iops_tiers endpoints

Draas get iops tiers

---

src/DRaaS/Client.php
src/DRaaS/ComputeResourcesClient.php
src/DRaaS/Entities/ComputeResources.php
src/DRaaS/SolutionClient.php

- Adds ComputeResourcesClient and functionality for get solutions/{id}/compute-resources

Draas get compute resources

---

src/SSL/Client.php
src/SSL/Entities/ValidationResult.php
src/SSL/ValidationClient.php
tests/Ssl/SslValidationTest.php

This branch will implement an SDK method for the new private SSL certificate validation endpoint in our SSL API

Implement new endpoint for validating private SSL certificates - Add SDK method

---

src/DRaaS/Client.php
src/DRaaS/ComputeResourcesClient.php
src/DRaaS/Entities/HardwarePlan.php
src/DRaaS/HardwarePlanClient.php
src/DRaaS/SolutionClient.php

125 get hardware plans

---

src/DRaaS/ComputeResourcesClient.php

map hardware_plan_id compute property friendly name

129 hardware plan id on compute resources

---

src/DRaaS/BillingTypeClient.php
src/DRaaS/Client.php
src/DRaaS/Entities/BillingType.php
src/DRaaS/Entities/Solution.php
src/DRaaS/SolutionClient.php

Adds milling type endpoints and surfaces billing type id on solutions endpoints

Adds billing type endpoints

---

src/DRaaS/Client.php
src/DRaaS/HardwarePlanClient.php
src/DRaaS/ReplicaClient.php

Set IOPS on solution replicas endpoint

130 set iops on replica

---

src/Billing/CloudCostClient.php

Added sdk helper method to handle units

Helper method added for Cloud Costs

---

src/Billing/RecurringCostClient.php

Allows for custom maps if class is extended.

Change Use Of Map To Static

---

src/DDoSX/CdnClient.php
src/DDoSX/WafClient.php

Reverting this fixes a backwards incompatible change

Fix Breaking Change

---

src/DDoSX/SslClient.php

The CA bundle was no longer getting sent over

Fix Breaking Change In DDoSX SSL Creation

---

.github/workflows/run-tests.yml

Fixes #192 
If we want to migrate from TravisCI to GitHub Actions, this config would give us the same functionality.

Add sample github actions config

---

src/eCloud/Entities/Instance.php
src/eCloud/InstanceClient.php

* @property string $applianceId
* @property boolean $locked
* @property integer $vcpuCores
* @property integer $ramCapacity

surface additional instance properties

---

src/Billing/RecurringCostClient.php

Fixed undefined property by using isset

---

src/DDoSX/AccessLogClient.php

I want to see 1 access log from 1 domain

199 add ddosx domain access logs show

---

src/DDoSX/AccessLogClient.php

I want to access logs by domain

198 ddosx domain access logs list

---

src/DDoSX/AccessLogClient.php

I want to see a single access log

197 add ddosx global access logs show

---

src/DDoSX/AccessLogClient.php

I want to be able to get a list of access logs from across my estate

196 add ddosx global access logs list

---

src/DDoSX/DomainClient.php

I want to be able to turn protection on & off

Add DDoSX DNS Toggling

---

src/DDoSX/DomainClient.php

This looks much cleaner and works in a similar way to other, newer clients

Make DDoSX Domain Hydration Dynamic

---

src/eCloud/BillingMetricClient.php
src/eCloud/Entities/BillingMetric.php

- surface category and price properties
- cast start/end dates as datetime objects

update billing metrics entity

---

src/SafeDNS/TemplateClient.php

These previously weren't being set

Add SafeDNS Template Filters

---

src/SafeDNS/TemplateClient.php

Add SafeDNS Template Deletion

---

src/SafeDNS/Entities/Nameserver.php
src/SafeDNS/Entities/Settings.php
src/SafeDNS/SettingsClient.php

Correct SafeDNS Settings Entity Mapping

---

src/Exception/ApiException.php

Correct & Add Docblocks

---

src/Loadbalancers/Entities/Bind.php
src/Loadbalancers/Entities/Ssl.php
src/Loadbalancers/Entities/Target.php
src/Loadbalancers/Entities/TargetGroup.php
src/Loadbalancers/Entities/Vip.php
src/Loadbalancers/ListenerClient.php
src/Loadbalancers/TargetClient.php
src/Loadbalancers/TargetGroupClient.php
src/Loadbalancers/VipClient.php

Just updating some erroneous LBv2 property names and correcting the mapping accordingly.

LBv2: Update properties and mapping

---

src/Loadbalancers/Entities/Cert.php
src/Loadbalancers/ListenerClient.php

Update property mapping to match new entity names

---

src/Loadbalancers/ListenerClient.php

I've basically copied the updateCert endpoint and changed the word Cert to Bind

Add updateBind function to ListenerClient

---

src/ThreatMonitoring/Client.php
src/ThreatMonitoring/Reporting/TopBruteForceUsernamesClient.php

- updated the TopBruteForceUsernamesClient import to match the case size,
- updated return type in TopBruteForceUsernamesClient->getList method,

Fix TopBruteForceUsernamesClient import case size

---

src/Client.php
tests/ClientTest.php

This will provide a non-breaking way of handling casted dates.
Closes #447

Add Handling Of Friendly To API DateTimes

---

src/ThreatMonitoring/AlertClient.php

This PR features a set of changes for alert toggling.

* SDK changes for Alert toggling

---

src/eCloud/Client.php
src/eCloud/Entities/Task.php
src/eCloud/TaskClient.php

Updates to UKFast\SDK\eCloud\Client to sideload the new TaskClient, and added Task entity.

Add eCloud Task Entity and Endpoints

---

src/eCloud/TaskClient.php

Removed duplicate getById method.

Removed duplicate method

---

src/eCloud/Entities/LoadBalancer.php
src/eCloud/LoadBalancerClient.php

Adds configId to load eCloud load balancers entity

249 make config id public

---

src/eCloud/Client.php
src/eCloud/Entities/IpAddress.php
src/eCloud/IpAddressesClient.php

Adds the IpAddressClient to the client under Client->ipAddresses()

251 Adds IpAddressClient to sdk

---

src/eCloud/Entities/Vip.php
src/eCloud/TaskClient.php
src/eCloud/VipClient.php

`Vip` entity remove `$loadBalancerNetworkId` add `$loadBalancerId`
`VipClient::getEntityMap` update map to remove `load_balancer_network_id` and add `load_balancer_id`

253 vips changes to submitted values

---

src/Account/Entities/Contact.php

Aids in MC passing larastan level 5

Adding dockblock comment.

---

src/eCloud/Entities/IpAddress.php
src/eCloud/IpAddressesClient.php

Adds types to the ip address client

adds types to ip address client

---

src/eCloud/Entities/VpnSession.php
src/eCloud/VpnSessionClient.php

add psk to vpn session entity map for patching the PSK

psk on vpn session

---

src/eCloud/AffinityRuleClient.php

Can now add and remove members from a rule

Adds more functionality for the affinity rule members

---

src/eCloud/AffinityRuleClient.php
src/eCloud/AffinityRuleMemberClient.php
src/eCloud/Client.php

Detached previous methods from the affinity rule client and moved them to the new affinity rule member client

Adds AffinityRuleMemberClient to the sdk

---

src/eCloud/AvailabilityZoneClient.php
src/eCloud/Client.php
src/eCloud/Entities/ResourceTier.php
src/eCloud/HostGroupClient.php
src/eCloud/ResourceTierClient.php

Adds the Resource Tier client to the SDK, also moves HostGroup entities to match new style

added resource tier client

---

src/Entity.php

This was a duplicate in a docblock

Fix A Typo

---

src/Account/Entities/Contact.php

added mobile, monitoringAlertsEmail, thresholdMonitoringAlertsEmail, monitoringAlertsSms and thresholdMonitoringAlertsSms properties to the Account Contact entity

Update Accounts Contact entity

---

src/eCloud/Entities/HostGroup.php

surfaces the windows_enabled property of host groups

surface windows enabled on hostgroup client

---

src/eCloud/Client.php
src/eCloud/Entities/Software.php
src/eCloud/SoftwareClient.php

software is now surfaced in the software client

Surfaces SoftwareClient

---

src/Loadbalancers/Entities/ErrorPage.php
src/Loadbalancers/ErrorPageClient.php

Updated Loadbalancer ErrorPage entity and entity map to add the listenerId

Added listenerId to Loadbalancers V2 ErrorPage entity and entity map

---

composer.json

set the phpunit version to 9.5, some used assertions were deprecated in v10

Set phpunit version

---

src/eCloud/BillingMetricClient.php
src/eCloud/Entities/BillingMetric.php

Adds resource_name to billing metrics.

added resource name

---

src/SSL/Client.php
src/SSL/DcvClient.php
src/SSL/Entities/DcvValidation.php

Validates by certificate ID and DCV type

Validates by certificate ID and DCV type

---

src/eCloud/Entities/Instance.php
src/eCloud/Entities/Volume.php
src/eCloud/InstanceClient.php
src/eCloud/VolumeClient.php

EC-1212 Portal: Surface encryption state on instance&volume collection/overview

Added is_encrypted property to instance and volume entities and maps.

---

src/eCloud/Entities/Image.php
src/eCloud/ImageClient.php

Added image_size attribute to Image Entity and property map

Added image_size attribute to Image Entity and property map

---

README.md

This is the right company name

Correct the company name

---

src/SSL/CertificateClient.php

Validate a CSR for a given certificate

Added Endpoint for CSR validation

---

src/eCloud/Entities/HostGroup.php

added usage, hostLimits and task properties to the HostGroup entity & entityMap

Added missing properties to the HostGroup entity

---

src/eCloud/AvailabilityZoneClient.php
src/eCloud/Client.php
src/eCloud/Entities/VpnGatewaySpecification.php
src/eCloud/VpnGatewaySpecificationClient.php

This PR adds the eCloud VPN Gateway Specification entity and clients

VPN Gateway Specifications

---

src/SSL/CertificateClient.php

This looks to have broken nightly builds on PHP 5.6

Remove PHP 5.6 incompatible code

---

src/eCloud/BillingHistoryClient.php
src/eCloud/Client.php
src/eCloud/Entities/BillingHistory.php

This PR adds the adds eCloud BillingHistory client and entity

eCloud BillingHistory

---

src/eCloud/Entities/VpnGateway.php

adds fqdn property to eClouds VpnGateway entity

adds fqdn property to eClouds VpnGateway entity

---

src/Account/Entities/Contact.php

This MR adds the hasRestrictedServerView property to the Account Contact entity

Update the Contact entity

---

src/eCloud/Client.php
src/eCloud/Entities/MonitoringGatewaySpecification.php
src/eCloud/MonitoringGatewaySpecificationClient.php

Add MonitoringGatewaySpecifications Client and Entity to eCloud

Add MonitoringGatewaySpecifications to eCloud

---

src/eCloud/Entities/AvailabilityZone.php

Surfaces an additional property for the AZs

Add state to the AZ entity

---

src/eCloud/Entities/HostSpec.php
src/eCloud/HostSpecClient.php

Revert "[49240] Surface available_host_quantity"
